package HelloWorldApp;


/**
* HelloWorldApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Helloworld.idl
* vendredi 24 octobre 2025 08 h 54 WEST
*/

public interface HelloOperations 
{
  String HelloMessage ();
  void HelloMessage (String newHelloMessage);
} // interface HelloOperations
